[versions]
androidx-lifecycle = "2.9.6"
androidx-navigation = "2.9.1"
coil = "3.3.0"
compose = "1.10.0-rc02"
filekit = "0.12.0"
hotReload = "1.0.0-beta05"
jdk = "21"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kstore = "1.0.0"
ktor = "3.3.3"
materialKolor = "4.0.5"

[libraries]
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

bandkit = { module = "uk.co.harnick:bandkit", version = "+" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-file = { module = "io.github.xxfast:kstore-file", version.ref = "kstore" }
kstore-storage = { module = "io.github.xxfast:kstore-storage", version.ref = "kstore" }

ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

reorderable = { module = "sh.calvin.reorderable:reorderable", version = "3.0.0" }

zip4j = { module = "net.lingala.zip4j:zip4j", version = "2.11.5" }

[plugins]
build-config = { id = "com.github.gmazzo.buildconfig", version = "5.6.8" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }

[bundles]
filekit = ["filekit-core", "filekit-dialogs-compose"]
ktor = ["ktor-cio", "ktor-client-encoding", "ktor-content-negotiation", "ktor-serialization-json"]
